# Generated by Django 5.1.7 on 2025-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=50)),
                ('user_answer', models.IntegerField()),
                ('correct_answer', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('attempts', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
