# Generated by Django 5.1.7 on 2025-04-05 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_tab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='operation_type',
            field=models.CharField(choices=[('multiplication', 'Умножение'), ('division', 'Деление'), ('squares', 'Квадраты чисел')], max_length=20),
        ),
    ]
